/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 9988e3938a64bef31bd6af7a886a2739)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/server");
		durableNamespaces: "Chat" | "Sandbox" | "MoltbotMcp" | "Registry";
	}
	interface Env {
		MOLTBOT_BUCKET: R2Bucket;
		BROWSER: Fetcher;
		AI: Ai;
		ASSETS: Fetcher;
		OPENAI_API_KEY: string;
		AI_GATEWAY_BASE_URL: string;
		AI_GATEWAY_API_KEY: string;
		ANTHROPIC_API_KEY: string;
		ANTHROPIC_BASE_URL: string;
		DEV_MODE: string;
		CLAWDBOT_BIND_MODE: string;
		MOLTBOT_GATEWAY_TOKEN: string;
		SANDBOX_SLEEP_AFTER: string;
		DEBUG_ROUTES: string;
		CDP_SECRET: string;
		WORKER_URL: string;
		TELEGRAM_BOT_TOKEN: string;
		TELEGRAM_DM_POLICY: string;
		DISCORD_BOT_TOKEN: string;
		DISCORD_DM_POLICY: string;
		SLACK_BOT_TOKEN: string;
		SLACK_APP_TOKEN: string;
		WHATSAPP_TOKEN: string;
		CF_ACCESS_TEAM_DOMAIN: string;
		CF_ACCESS_AUD: string;
		R2_ACCESS_KEY_ID: string;
		R2_SECRET_ACCESS_KEY: string;
		CF_ACCOUNT_ID: string;
		Chat: DurableObjectNamespace<import("./worker/server").Chat>;
		Sandbox: DurableObjectNamespace<import("./worker/server").Sandbox>;
		MoltbotMcp: DurableObjectNamespace<import("./worker/server").MoltbotMcp>;
		Registry: DurableObjectNamespace<import("./worker/server").Registry>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "OPENAI_API_KEY" | "AI_GATEWAY_BASE_URL" | "AI_GATEWAY_API_KEY" | "ANTHROPIC_API_KEY" | "ANTHROPIC_BASE_URL" | "DEV_MODE" | "CLAWDBOT_BIND_MODE" | "MOLTBOT_GATEWAY_TOKEN" | "SANDBOX_SLEEP_AFTER" | "DEBUG_ROUTES" | "CDP_SECRET" | "WORKER_URL" | "TELEGRAM_BOT_TOKEN" | "TELEGRAM_DM_POLICY" | "DISCORD_BOT_TOKEN" | "DISCORD_DM_POLICY" | "SLACK_BOT_TOKEN" | "SLACK_APP_TOKEN" | "WHATSAPP_TOKEN" | "CF_ACCESS_TEAM_DOMAIN" | "CF_ACCESS_AUD" | "R2_ACCESS_KEY_ID" | "R2_SECRET_ACCESS_KEY" | "CF_ACCOUNT_ID">> {}
}
